const styleLink=document.createElement("link");styleLink.rel="stylesheet";styleLink.href="/chauffeur-form.css?v=20260728-pwa-1";document.head.append(styleLink);
const WAIT_RATE=20;
const tariffs=[{min:1,max:3,base:24.13,perKm:.49},{min:4,max:6,base:28.35,perKm:.503},{min:7,max:9,base:32.57,perKm:.515},{min:10,max:20,base:32.57,perKm:.515,extraPassengerRate:.2}];
const form=document.querySelector("#chauffeurForm"),date=document.querySelector("#chauffeurDate"),whatsapp=document.querySelector("#chauffeurWhatsApp"),status=document.querySelector("#chauffeurStatus");
const fields={from:document.querySelector("#chauffeurFrom"),to:document.querySelector("#chauffeurTo"),return:document.querySelector("#chauffeurReturn")};
const selected={from:null,to:null,return:null};const timers={};let lastQuote=null;
const now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;date.min=iso(now);date.value=iso(tomorrow);
const escapeHtml=value=>String(value||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
for(const [key,input] of Object.entries(fields)){input.addEventListener("input",()=>{selected[key]=null;lastQuote=null;document.querySelector("#chauffeurQuote").hidden=true;whatsapp.setAttribute("aria-disabled","true");clearTimeout(timers[key]);if(input.value.trim().length<2){results(key).hidden=true;return}timers[key]=setTimeout(()=>search(key),280)});input.addEventListener("focus",()=>{if(results(key).children.length)results(key).hidden=false})}
document.addEventListener("click",event=>{if(!event.target.closest(".place-search"))document.querySelectorAll(".chauffeur-results").forEach(x=>x.hidden=true)});
function results(key){return document.querySelector(`[data-results="${key}"]`)}
async function search(key){const box=results(key);try{const response=await fetch("/api/place-autocomplete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:fields[key].value.trim(),language:document.documentElement.lang,placeType:""})});const payload=await response.json();if(!response.ok)throw new Error();const suggestions=payload.suggestions||[];box.innerHTML=suggestions.length?suggestions.map((s,i)=>`<button type="button" data-index="${i}"><strong>${escapeHtml(s.mainText||s.text)}</strong><span>${escapeHtml(s.secondaryText||s.text)}</span></button>`).join(""):`<span>Ничего не найдено</span>`;box.hidden=false;box.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>choose(key,suggestions[Number(button.dataset.index)])))}catch{box.innerHTML="<span>Не удалось выполнить поиск</span>";box.hidden=false}}
async function choose(key,suggestion){const box=results(key);box.hidden=true;fields[key].value=suggestion.mainText||suggestion.text;status.textContent="Получаю адрес…";try{const response=await fetch("/api/place-details",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({placeId:suggestion.placeId,language:document.documentElement.lang})});const payload=await response.json();if(!response.ok)throw new Error();selected[key]=payload.place;fields[key].value=payload.place.formattedAddress||payload.place.displayName;status.textContent=""}catch{selected[key]=null;status.textContent="Не удалось получить точный адрес. Выберите его ещё раз."}}
async function route(origin,destination){const response=await fetch("/api/route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin,destination,language:document.documentElement.lang})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||"route_failed");return payload}
form.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity())return;if(!selected.from||!selected.to||!selected.return){status.textContent="Выберите все три адреса из выпадающего списка.";return}const passengers=Number(form.elements.passengers.value),hours=Number(form.elements.hours.value),tariff=tariffs.find(x=>passengers>=x.min&&passengers<=x.max);if(!tariff)return;status.textContent="Рассчитываю дорожное расстояние…";try{const [outbound,inbound]=await Promise.all([route(selected.from,selected.to),route(selected.to,selected.return)]);const distance=outbound.distanceKm+inbound.distanceKm;const routePrice=globalThis.GoTransferPricing.calculateTransferPrice(tariff,distance,passengers);const waitPrice=hours*WAIT_RATE;const total=routePrice+waitPrice;lastQuote={distance,routePrice,waitPrice,total,hours,passengers};document.querySelector("#chauffeurDistance").textContent=`${distance.toFixed(1)} км`;document.querySelector("#chauffeurRoutePrice").textContent=`${routePrice} €`;document.querySelector("#chauffeurWaitPrice").textContent=`${waitPrice} €`;document.querySelector("#chauffeurTotal").textContent=`${total} €`;document.querySelector("#chauffeurQuote").hidden=false;status.textContent="Расчёт готов. Итог можно отправить оператору.";updateWhatsapp();whatsapp.setAttribute("aria-disabled","false")}catch{lastQuote=null;status.textContent="Не удалось рассчитать маршрут. Проверьте адреса или напишите оператору.";whatsapp.setAttribute("aria-disabled","true")}});
function updateWhatsapp(){if(!lastQuote)return;const data=new FormData(form);const message=["Здравствуйте! Хочу заказать автомобиль с персональным водителем в Анталии.",`Маршрут: ${fields.from.value} → ${fields.to.value} → ${fields.return.value}`,`Дата и время: ${data.get("date")} ${data.get("time")}`,`Общее расстояние: ${lastQuote.distance.toFixed(1)} км`,`Поездка по маршруту: ${lastQuote.routePrice} €`,`Ожидание: ${lastQuote.hours} ч × ${WAIT_RATE} € = ${lastQuote.waitPrice} €`,`Пассажиры: ${lastQuote.passengers}`,`Итоговая стоимость: ${lastQuote.total} €`,`Комментарий: ${data.get("route")||"нет"}`].join("\n");whatsapp.href=`https://wa.me/905346801828?text=${encodeURIComponent(message)}`}
