window.GoTransferEditorial = {
  articles: [
    {
      slug: "first-time-in-antalya",
      image: "/images/places/kaleici.jpg",
      published: "2026-08-01",
      reading: 6,
      category: {ru:"Советы",en:"Tips",tr:"İpuçları",de:"Tipps",ar:"نصائح"},
      title: {
        ru:"Первый день в Анталии: спокойный маршрут без спешки",
        en:"Your first day in Antalya: an unhurried itinerary",
        tr:"Antalya'daki ilk gününüz: sakin bir rota",
        de:"Der erste Tag in Antalya: eine entspannte Route",
        ar:"يومكم الأول في أنطاليا: مسار هادئ بلا عجلة"
      },
      description: {
        ru:"Калеичи, море, хороший обед и несколько панорамных остановок — как познакомиться с городом в комфортном ритме.",
        en:"Kaleiçi, the sea, a good lunch and panoramic stops — a comfortable introduction to the city.",
        tr:"Kaleiçi, deniz, güzel bir öğle yemeği ve panoramik duraklarla şehri rahatça keşfedin.",
        de:"Kaleiçi, Meer, ein gutes Mittagessen und Panoramastopps — Antalya in angenehmem Tempo.",
        ar:"كاليتشي والبحر وغداء جيد ومحطات بانورامية للتعرّف إلى المدينة براحة."
      },
      body: {
        ru:["Первое знакомство с Анталией лучше не превращать в марафон. Начните с ранней прогулки по Калеичи, пока старые улицы ещё тихие.","После старого порта оставьте время на обед и побережье. Персональный водитель особенно удобен, если вы путешествуете с детьми или хотите менять программу по погоде.","На обратном пути выберите одну панорамную остановку: Нижний Дюден или берег Коньяалты. Так день останется насыщенным, но не утомительным."],
        en:["A first meeting with Antalya should not become a marathon. Begin with an early walk through Kaleiçi while its old lanes are still quiet.","After the old harbour, leave time for lunch and the coast. A private chauffeur is useful for families and for adapting the day to the weather.","Choose one panoramic stop on the return: Lower Düden or the Konyaaltı coast. The day stays memorable without becoming tiring."],
        tr:["Antalya ile ilk tanışmanızı bir maratona çevirmeyin. Eski sokaklar sakinken Kaleiçi'nde erken bir yürüyüşle başlayın.","Eski limandan sonra öğle yemeği ve sahil için zaman ayırın. Çocuklarla seyahat ederken veya programı havaya göre değiştirmek istediğinizde özel şoför büyük rahatlık sağlar.","Dönüşte Aşağı Düden ya da Konyaaltı kıyısında tek bir panoramik durak seçin. Böylece gün dolu ama yorucu olmaz."],
        de:["Das erste Kennenlernen von Antalya sollte kein Marathon sein. Beginnen Sie früh in Kaleiçi, solange die alten Gassen noch ruhig sind.","Nach dem alten Hafen bleibt Zeit für Mittagessen und Küste. Ein privater Chauffeur ist besonders angenehm für Familien und flexible Wetterplanung.","Wählen Sie auf dem Rückweg einen Panoramastopp: den Unteren Düden oder die Küste von Konyaaltı. So bleibt der Tag reich, aber entspannt."],
        ar:["لا تجعلوا لقاءكم الأول مع أنطاليا سباقاً. ابدؤوا بنزهة مبكرة في كاليتشي بينما الأزقة القديمة هادئة.","بعد الميناء القديم اتركوا وقتاً للغداء والساحل. السائق الخاص مريح للعائلات ولتعديل البرنامج حسب الطقس.","اختاروا محطة بانورامية واحدة في العودة: شلال دودان السفلي أو ساحل كونيالتي، ليبقى اليوم غنياً بلا إرهاق."]
      }
    },
    {
      slug:"demre-myra-kekova-guide", image:"/images/places/kekova.png", published:"2026-07-24", reading:8,
      category:{ru:"Маршруты",en:"Routes",tr:"Rotalar",de:"Routen",ar:"مسارات"},
      title:{ru:"Демре, Мира и Кекова за один день",en:"Demre, Myra and Kekova in one day",tr:"Bir günde Demre, Myra ve Kekova",de:"Demre, Myra und Kekova an einem Tag",ar:"ديمره وميرا وككوفا في يوم واحد"},
      description:{ru:"Как соединить древнюю Ликию, храм Святого Николая и морскую прогулку без жёсткого экскурсионного графика.",en:"How to combine ancient Lycia, Saint Nicholas Church and a boat trip without a rigid tour schedule.",tr:"Antik Likya, Aziz Nikolaos Kilisesi ve tekne gezisini katı bir tur programı olmadan birleştirin.",de:"Antikes Lykien, die Nikolauskirche und eine Bootsfahrt ohne starren Zeitplan verbinden.",ar:"جمع ليكيا القديمة وكنيسة القديس نيقولا ورحلة بحرية بلا جدول سياحي صارم."},
      body:{ru:["Маршрут длинный, поэтому выезжать лучше утром. Первой остановкой удобно сделать Миру, пока археологическая зона не перегрета.","В Демре оставьте отдельное время для церкви Святого Николая и спокойного обеда. Морскую часть в Кекове стоит согласовать заранее.","Индивидуальный автомобиль позволяет сократить или продлить любую остановку и вернуться в отель без ожидания группы."],en:["This is a long route, so an early start works best. Visit Myra first before the archaeological site becomes hot.","Allow separate time for Saint Nicholas Church and an unhurried lunch in Demre. Arrange the Kekova boat section in advance.","A private vehicle lets you shorten or extend every stop and return without waiting for a group."],tr:["Rota uzundur; erken çıkmak en iyisidir. Arkeolojik alan ısınmadan önce Myra'yı ziyaret edin.","Demre'de Aziz Nikolaos Kilisesi ve sakin bir öğle yemeği için ayrı zaman bırakın. Kekova tekne bölümünü önceden planlayın.","Özel araç her durağı uzatmanıza veya kısaltmanıza ve grup beklemeden dönmenize imkân verir."],de:["Die Route ist lang, daher empfiehlt sich ein früher Start. Besuchen Sie Myra zuerst, bevor es heiß wird.","Planen Sie in Demre eigene Zeit für die Nikolauskirche und ein ruhiges Mittagessen ein. Die Bootsfahrt bei Kekova sollte vorab abgestimmt werden.","Mit einem privaten Fahrzeug lässt sich jeder Stopp flexibel verlängern oder verkürzen."],ar:["المسار طويل، لذا يُفضّل الانطلاق باكراً وزيارة ميرا قبل اشتداد الحر.","خصصوا وقتاً مستقلاً لكنيسة القديس نيقولا وغداء هادئ في ديمره، ورتبوا الجزء البحري في ككوفا مسبقاً.","السيارة الخاصة تتيح تمديد أي محطة أو اختصارها والعودة من دون انتظار مجموعة."]}
    },
    {
      slug:"travelling-with-children-antalya", image:"/images/chauffeur/family.png", published:"2026-07-12", reading:5,
      category:{ru:"Семья",en:"Family",tr:"Aile",de:"Familie",ar:"العائلة"},
      title:{ru:"По Анталии с детьми: комфортный день в дороге",en:"Antalya with children: a comfortable day on the road",tr:"Çocuklarla Antalya: yolda konforlu bir gün",de:"Antalya mit Kindern: entspannt unterwegs",ar:"أنطاليا مع الأطفال: يوم مريح على الطريق"},
      description:{ru:"Детские кресла, короткие переезды, пляжи и остановки — практический план семейной поездки.",en:"Child seats, short drives, beaches and breaks — a practical family travel plan.",tr:"Çocuk koltukları, kısa sürüşler, plajlar ve molalarla pratik bir aile planı.",de:"Kindersitze, kurze Fahrten, Strände und Pausen — ein praktischer Familienplan.",ar:"مقاعد أطفال وتنقلات قصيرة وشواطئ واستراحات لخطة عائلية عملية."},
      body:{ru:["Семейный маршрут начинается не с количества мест, а с ритма ребёнка. Планируйте одну главную цель и две короткие остановки.","Заказывайте подходящее кресло заранее и сообщайте возраст детей. В жаркие месяцы активную часть лучше переносить на утро.","Автомобиль с водителем даёт место для вещей и возможность изменить маршрут без стресса, если ребёнку нужен отдых."],en:["A family itinerary starts with the child's rhythm, not the number of attractions. Plan one main destination and two short stops.","Reserve the correct child seat in advance and share each child's age. In hot months, keep active visits for the morning.","A chauffeur-driven car provides space for luggage and lets the family change plans when a child needs a break."],tr:["Aile rotası görülecek yer sayısıyla değil, çocuğun ritmiyle başlar. Bir ana hedef ve iki kısa durak planlayın.","Uygun çocuk koltuğunu önceden isteyin ve çocukların yaşını bildirin. Sıcak aylarda hareketli bölümü sabaha alın.","Şoförlü araç eşyalara yer sağlar ve çocuk dinlenmek istediğinde rotayı stressizce değiştirir."],de:["Eine Familienroute orientiert sich am Rhythmus des Kindes, nicht an der Zahl der Ziele. Planen Sie ein Hauptziel und zwei kurze Stopps.","Bestellen Sie den passenden Kindersitz vorab und nennen Sie das Alter. Im Sommer gehören aktive Besuche in den Morgen.","Ein Chauffeurfahrzeug bietet Platz und erlaubt spontane Pausen ohne Stress."],ar:["يبدأ مسار العائلة بإيقاع الطفل لا بعدد الأماكن. خططوا لهدف رئيسي ومحطتين قصيرتين.","اطلبوا المقعد المناسب مسبقاً واذكروا أعمار الأطفال، واجعلوا النشاط في الصباح خلال الحر.","توفر السيارة مع سائق مساحة للأغراض ومرونة لتغيير المسار عندما يحتاج الطفل إلى الراحة."]}
    }
  ],
  reviewPhotos: [
    {src:"/images/reviews/fleet-coast.jpg",alt:{ru:"Автомобили GoTransfer на побережье",en:"GoTransfer vehicles by the coast",tr:"Sahilde GoTransfer araçları",de:"GoTransfer Fahrzeuge an der Küste",ar:"سيارات GoTransfer على الساحل"}},
    {src:"/images/reviews/vip-welcome-no-face.jpg",alt:{ru:"Встреча пассажира у VIP-автомобиля",en:"Passenger welcome at a VIP vehicle",tr:"VIP araçta yolcu karşılama",de:"Empfang am VIP-Fahrzeug",ar:"استقبال الراكب عند سيارة VIP"}},
    {src:"/images/reviews/vip-cabin.jpg",alt:{ru:"Премиальный пассажирский салон",en:"Premium passenger cabin",tr:"Premium yolcu kabini",de:"Premium-Fahrgastraum",ar:"مقصورة ركاب فاخرة"},crop:true},
    {src:"/images/reviews/vip-van.jpg",alt:{ru:"VIP-автомобиль GoTransfer",en:"GoTransfer VIP vehicle",tr:"GoTransfer VIP aracı",de:"GoTransfer VIP-Fahrzeug",ar:"سيارة GoTransfer VIP"},crop:true}
  ],
  reviews: [
    {id:"airport-on-time",name:{ru:"Клиент GoTransfer",en:"GoTransfer client",tr:"GoTransfer müşterisi",de:"GoTransfer Kunde",ar:"عميل GoTransfer"},route:{ru:"Аэропорт — отель",en:"Airport — hotel",tr:"Havalimanı — otel",de:"Flughafen — Hotel",ar:"المطار — الفندق"},text:{ru:"Трансфер аэропорт — отель прошёл отлично. Водитель написал заранее, встретил с табличкой, всё чётко и без задержек. Рекомендую!",en:"The airport-to-hotel transfer went perfectly. The driver wrote in advance, met us with a sign, and everything was punctual and smooth. Recommended!",tr:"Havalimanı-otel transferi mükemmel geçti. Şoför önceden yazdı, tabelayla karşıladı; her şey zamanında ve sorunsuzdu. Tavsiye ederim!",de:"Der Transfer vom Flughafen zum Hotel verlief perfekt. Der Fahrer schrieb vorher, empfing uns mit Namensschild und alles war pünktlich. Empfehlenswert!",ar:"كانت خدمة النقل من المطار إلى الفندق ممتازة. تواصل السائق مسبقاً واستقبلنا بلوحة اسم، وكل شيء كان دقيقاً ومن دون تأخير. أوصي بها!"},source:"WhatsApp"},
    {id:"kappadokia",name:{ru:"Клиент GoTransfer",en:"GoTransfer client",tr:"GoTransfer müşterisi",de:"GoTransfer Kunde",ar:"عميل GoTransfer"},route:{ru:"Поездка в Каппадокию",en:"Cappadocia trip",tr:"Kapadokya gezisi",de:"Kappadokien-Reise",ar:"رحلة كابادوكيا"},text:{ru:"Ездили на экскурсию в Каппадокию. Машина отличная, водитель — профессионал своего дела. Дорога прошла легко и интересно! Обязательно обратимся ещё.",en:"We travelled to Cappadocia. The vehicle was excellent and the driver a true professional. The journey was easy and interesting. We will definitely book again.",tr:"Kapadokya gezisine çıktık. Araç harikaydı, şoför gerçek bir profesyoneldi. Yolculuk rahat ve keyifli geçti. Kesinlikle tekrar tercih edeceğiz.",de:"Wir waren in Kappadokien. Das Fahrzeug war ausgezeichnet und der Fahrer ein echter Profi. Die Fahrt war angenehm und interessant. Sehr gerne wieder.",ar:"ذهبنا في رحلة إلى كابادوكيا. كانت السيارة ممتازة والسائق محترفاً. مرّ الطريق بسهولة ومتعة، وسنتواصل معكم بالتأكيد مرة أخرى."},source:"WhatsApp"},
    {id:"child-seat",name:{ru:"Семья с ребёнком",en:"Family with a child",tr:"Çocuklu aile",de:"Familie mit Kind",ar:"عائلة مع طفل"},route:{ru:"Аэропорт — отель",en:"Airport — hotel",tr:"Havalimanı — otel",de:"Flughafen — Hotel",ar:"المطار — الفندق"},text:{ru:"Спасибо за помощь с детским креслом! Для нас это было очень важно. Всё подготовили заранее, ребёнок ехал в безопасности и комфорте.",en:"Thank you for arranging the child seat. It was very important to us. Everything was prepared in advance and our child travelled safely and comfortably.",tr:"Çocuk koltuğu konusundaki yardımınız için teşekkürler. Bizim için çok önemliydi. Her şey önceden hazırlandı; çocuğumuz güvenli ve rahat yolculuk etti.",de:"Vielen Dank für den Kindersitz. Das war uns sehr wichtig. Alles war vorbereitet und unser Kind fuhr sicher und bequem.",ar:"شكراً لتوفير مقعد الطفل، كان ذلك مهماً جداً لنا. جرى تجهيز كل شيء مسبقاً وسافر طفلنا بأمان وراحة."},source:"WhatsApp"},
    {id:"anna-transfer",name:{ru:"Клиент из Instagram",en:"Instagram client",tr:"Instagram müşterisi",de:"Instagram-Kunde",ar:"عميل إنستغرام"},route:{ru:"Трансфер по Анталии",en:"Antalya transfer",tr:"Antalya transferi",de:"Transfer in Antalya",ar:"نقل داخل أنطاليا"},text:{ru:"Анна, благодарю вас за прекрасный трансфер. Нам понравилось всё: отличная, чистая и красивая машина, приятный, пунктуальный и профессиональный водитель.",en:"Anna, thank you for the wonderful transfer. We liked everything: an excellent, clean and beautiful vehicle and a pleasant, punctual, professional driver.",tr:"Anna, harika transfer için teşekkür ederiz. Her şeyi çok beğendik: temiz ve güzel araç, nazik, dakik ve profesyonel şoför.",de:"Anna, vielen Dank für den wunderbaren Transfer. Uns gefiel alles: ein sauberes, schönes Fahrzeug und ein freundlicher, pünktlicher, professioneller Fahrer.",ar:"آنا، شكراً على خدمة النقل الرائعة. أعجبنا كل شيء: سيارة ممتازة ونظيفة وجميلة، وسائق لطيف ودقيق ومحترف."},date:"2023-08-02",source:"Instagram"},
    {id:"quick-solution",name:{ru:"Клиент из Instagram",en:"Instagram client",tr:"Instagram müşterisi",de:"Instagram-Kunde",ar:"عميل إنستغرام"},route:{ru:"Стамбул",en:"Istanbul",tr:"İstanbul",de:"Istanbul",ar:"إسطنبول"},text:{ru:"Спасибо вам за быстрое решение моей проблемы! Не многие могут быстро и без лишних разговоров предоставить услугу. Сама имею бизнес в Стамбуле — знаю, о чём говорю.",en:"Thank you for solving my problem so quickly. Few people can provide a service promptly and without unnecessary discussion. I run a business in Istanbul, so I know what I am talking about.",tr:"Sorunumu bu kadar hızlı çözdüğünüz için teşekkür ederim. Çok az kişi gereksiz konuşmadan hızlı hizmet sunabiliyor. İstanbul'da işletmem var; ne söylediğimi biliyorum.",de:"Vielen Dank für die schnelle Lösung meines Problems. Nur wenige bieten ohne Umwege so schnell einen Service. Ich führe selbst ein Unternehmen in Istanbul und weiß, wovon ich spreche.",ar:"شكراً لحل مشكلتي بسرعة. قليلون يستطيعون تقديم الخدمة سريعاً ومن دون نقاشات زائدة. لدي عمل في إسطنبول وأعرف ما أتحدث عنه."},source:"Instagram"},
    {id:"comfortable-cars",name:{ru:"Клиент GoTransfer",en:"GoTransfer client",tr:"GoTransfer müşterisi",de:"GoTransfer Kunde",ar:"عميل GoTransfer"},route:{ru:"Индивидуальный трансфер",en:"Private transfer",tr:"Özel transfer",de:"Privattransfer",ar:"نقل خاص"},text:{ru:"Очень комфортные автомобили, чистые и с кондиционером. Водитель аккуратный и вежливый. Поездка оставила только приятные впечатления.",en:"Very comfortable, clean, air-conditioned vehicles. The driver was careful and polite. The trip left only pleasant impressions.",tr:"Araçlar çok konforlu, temiz ve klimalıydı. Şoför dikkatli ve nazikti. Yolculuktan yalnızca güzel izlenimlerle ayrıldık.",de:"Sehr komfortable, saubere und klimatisierte Fahrzeuge. Der Fahrer war umsichtig und höflich. Die Fahrt hinterließ nur gute Eindrücke.",ar:"السيارات مريحة جداً ونظيفة ومكيفة. كان السائق حذراً ومهذباً، وتركت الرحلة لدينا انطباعات جميلة فقط."},source:"WhatsApp"}
  ]
};
window.GoTransferEditorial.reviewEvidence=Array.from({length:18},(_,index)=>({src:`/images/reviews/evidence-${String(index+1).padStart(2,"0")}.jpg`,alt:{ru:`Оригинальный скриншот отзыва ${index+1}`,en:`Original review screenshot ${index+1}`,tr:`Orijinal yorum ekran görüntüsü ${index+1}`,de:`Originaler Bewertungs-Screenshot ${index+1}`,ar:`لقطة شاشة أصلية للرأي ${index+1}`}}));
window.dispatchEvent(new CustomEvent("gotransfer:editorialready"));
