(function(){
const titles={
en:["Demre — Myra — Church of Saint Nicholas","Demre — Myra — Kekova","Kaş","Kaş and Kaputaş Beach","Kaş and Patara","Patara and the Ancient City of Patara","Olympos — Çıralı — Flames of Chimaera","Phaselis and Tekirova","Kemer and the Tahtalı Cable Car","Side and Manavgat Waterfall","Aspendos and Perge","Side and Aspendos","Green Canyon","Sapadere Canyon","Alanya: castle, cable car and harbour","Orthodox Antalya: Saint Alypios Church and Kaleiçi","In the footsteps of Saint Nicholas: Patara — Myra — Demre","Orthodox heritage of Alanya","Termessos and Düden Waterfall","Köprülü Canyon and Aspendos","Antalya waterfalls and Kaleiçi","Lycian Way and Gelidonya Lighthouse","Lycian Way: Çıralı to Olympos","Adrasan and Suluada Island","Göynük Canyon and the Lycian Way","Arykanda — Limyra — Finike","Alanya, Dim Cave and Dim River","Ancient Syedra and Alanya","Karain Cave and Termessos","Perge, Kurşunlu Waterfall and Antalya Museum","Antalya Museum and Kaleiçi","Cleopatra Beach, Damlataş Cave and Alanya Castle","Tekirova and Three Islands boat trip","Phaselis and Mount Tahtalı","Beldibi Cave, Göynük Canyon and Kemer","Zeytintaşı Cave and Aspendos","Rhodiapolis — Limyra — Finike","Kekova, Kaleköy and Üçağız","The Land of Legends and Belek"],
tr:["Demre — Myra — Aziz Nikolaos Kilisesi","Demre — Myra — Kekova","Kaş","Kaş ve Kaputaş Plajı","Kaş ve Patara","Patara ve Patara Antik Kenti","Olympos — Çıralı — Yanartaş","Phaselis ve Tekirova","Kemer ve Tahtalı Teleferiği","Side ve Manavgat Şelalesi","Aspendos ve Perge","Side ve Aspendos","Green Canyon","Sapadere Kanyonu","Alanya: kale, teleferik ve liman","Ortodoks Antalya: Aziz Alypios Kilisesi ve Kaleiçi","Aziz Nikolaos'un izinde: Patara — Myra — Demre","Alanya'nın Ortodoks mirası","Termessos ve Düden Şelalesi","Köprülü Kanyon ve Aspendos","Antalya şelaleleri ve Kaleiçi","Likya Yolu ve Gelidonya Feneri","Likya Yolu: Çıralı — Olympos","Adrasan ve Suluada","Göynük Kanyonu ve Likya Yolu","Arykanda — Limyra — Finike","Alanya, Dim Mağarası ve Dim Çayı","Syedra Antik Kenti ve Alanya","Karain Mağarası ve Termessos","Perge, Kurşunlu Şelalesi ve Antalya Müzesi","Antalya Müzesi ve Kaleiçi","Kleopatra Plajı, Damlataş Mağarası ve Alanya Kalesi","Tekirova ve Üç Adalar tekne turu","Phaselis ve Tahtalı Dağı","Beldibi Mağarası, Göynük Kanyonu ve Kemer","Zeytintaşı Mağarası ve Aspendos","Rhodiapolis — Limyra — Finike","Kekova, Kaleköy ve Üçağız","The Land of Legends ve Belek"],
de:["Demre — Myra — Kirche des Heiligen Nikolaus","Demre — Myra — Kekova","Kaş","Kaş und Kaputaş-Strand","Kaş und Patara","Patara und die antike Stadt Patara","Olympos — Çıralı — Flammen der Chimäre","Phaselis und Tekirova","Kemer und die Tahtalı-Seilbahn","Side und Manavgat-Wasserfall","Aspendos und Perge","Side und Aspendos","Green Canyon","Sapadere Canyon","Alanya: Burg, Seilbahn und Hafen","Orthodoxes Antalya: Kirche des Heiligen Alypios und Kaleiçi","Auf den Spuren des Heiligen Nikolaus: Patara — Myra — Demre","Orthodoxes Erbe von Alanya","Termessos und Düden-Wasserfall","Köprülü Canyon und Aspendos","Wasserfälle von Antalya und Kaleiçi","Lykischer Weg und Leuchtturm Gelidonya","Lykischer Weg: Çıralı — Olympos","Adrasan und die Insel Suluada","Göynük Canyon und Lykischer Weg","Arykanda — Limyra — Finike","Alanya, Dim-Höhle und Dim-Fluss","Antikes Syedra und Alanya","Karain-Höhle und Termessos","Perge, Kurşunlu-Wasserfall und Antalya-Museum","Antalya-Museum und Kaleiçi","Kleopatra-Strand, Damlataş-Höhle und Burg Alanya","Tekirova und Bootsfahrt zu den Drei Inseln","Phaselis und Berg Tahtalı","Beldibi-Höhle, Göynük Canyon und Kemer","Zeytintaşı-Höhle und Aspendos","Rhodiapolis — Limyra — Finike","Kekova, Kaleköy und Üçağız","The Land of Legends und Belek"],
ar:["ديمره — ميرا — كنيسة القديس نيقولاوس","ديمره — ميرا — كيكوفا","كاش","كاش وشاطئ كابوتاش","كاش وباتارا","باتارا ومدينة باتارا الأثرية","أوليمبوس — تشيرالي — نيران خيميرا","فاسيليس وتكيروفا","كيمر وتلفريك تهتالي","سيدا وشلال مانافغات","أسبندوس وبيرغه","سيدا وأسبندوس","الوادي الأخضر","وادي ساباديره","ألانيا: القلعة والتلفريك والميناء","أنطاليا الأرثوذكسية: كنيسة القديس أليبيوس وكاليتشي","على خطى القديس نيقولاوس: باتارا — ميرا — ديمره","التراث الأرثوذكسي في ألانيا","ترميسوس وشلال دودن","وادي كوبرولو وأسبندوس","شلالات أنطاليا وكاليتشي","مسار ليقيا ومنارة جيلدونيا","مسار ليقيا: تشيرالي — أوليمبوس","أدراسان وجزيرة سولودا","وادي غوينوك ومسار ليقيا","أريكاندا — ليميرا — فينيكه","ألانيا وكهف ديم ونهر ديم","مدينة سيدرا القديمة وألانيا","كهف كارين وترميسوس","بيرغه وشلال كورشونلو ومتحف أنطاليا","متحف أنطاليا وكاليتشي","شاطئ كليوباترا وكهف داملاتاش وقلعة ألانيا","تيكيروفا ورحلة الجزر الثلاث","فاسيليس وجبل تهتالي","كهف بيلديبي ووادي غوينوك وكيمر","كهف زيتينتاش وأسبندوس","روديابوليس — ليميرا — فينيكه","كيكوفا وكاليكوي وأوتشاغيز","ذا لاند أوف ليجندز وبيليك"]
};
const page={
ru:{title:"Однодневные VIP-путешествия по Анталийскому побережью — GoTransfer",meta:"Однодневные индивидуальные VIP-путешествия из Анталии с персональным водителем.",back:"← Услуги",kicker:"GO TRANSFER · ИНДИВИДУАЛЬНЫЕ ПОЕЗДКИ",hero:"Однодневные VIP-путешествия по Анталийскому побережью",lead:"Утром мы заберём вас из отеля, проведём день на выбранном маршруте и вечером вернём обратно. Только ваш автомобиль, персональный водитель и гибкая программа.",choose:"Выбрать VIP-путешествие",listKicker:"УТРОМ ВЫЕЗД · ВЕЧЕРОМ ВОЗВРАЩЕНИЕ",listTitle:"Выберите свой день на побережье",listText:"Более двадцати индивидуальных маршрутов без групп, автобусов и жёсткого расписания.",details:"Подробнее",book:"Забронировать VIP-путешествие",duration:"ИНДИВИДУАЛЬНО",ctaKicker:"ИНДИВИДУАЛЬНАЯ ПРОГРАММА",ctaTitle:"Подстроим маршрут под ваши интересы",ctaText:"Можно изменить порядок остановок, добавить ресторан, пляж или смотровую площадку. Оператор рассчитает индивидуальную стоимость.",ctaButton:"Обсудить маршрут в WhatsApp",home:"Главная",services:"Все услуги",backMobile:"Назад"},
en:{title:"Private VIP day journeys along the Antalya coast — GoTransfer",meta:"Private VIP day journeys from Antalya with a personal chauffeur.",back:"← Services",kicker:"GO TRANSFER · PRIVATE DAY JOURNEYS",hero:"Private VIP day journeys along the Antalya coast",lead:"We collect you from your hotel in the morning, follow your chosen itinerary and return in the evening. Your private vehicle, personal chauffeur and a flexible programme.",choose:"Choose a VIP journey",listKicker:"MORNING DEPARTURE · EVENING RETURN",listTitle:"Choose your day on the coast",listText:"More than twenty private itineraries without groups, coaches or a rigid timetable.",details:"View details",book:"Book the VIP journey",duration:"PRIVATE",ctaKicker:"TAILORED PROGRAMME",ctaTitle:"We tailor the route to your interests",ctaText:"Change the order of stops or add a restaurant, beach or viewpoint. The operator will prepare a personal quote.",ctaButton:"Discuss the route on WhatsApp",home:"Home",services:"All services",backMobile:"Back"},
tr:{title:"Antalya kıyısında günübirlik VIP yolculuklar — GoTransfer",meta:"Antalya'dan kişisel şoförlü özel günübirlik VIP yolculuklar.",back:"← Hizmetler",kicker:"GO TRANSFER · ÖZEL GÜNÜBİRLİK YOLCULUKLAR",hero:"Antalya kıyısında günübirlik VIP yolculuklar",lead:"Sabah sizi otelinizden alır, seçtiğiniz rotayı izler ve akşam geri getiririz. Size özel araç, kişisel şoför ve esnek program.",choose:"VIP yolculuk seçin",listKicker:"SABAH ÇIKIŞ · AKŞAM DÖNÜŞ",listTitle:"Kıyıdaki gününüzü seçin",listText:"Grup, otobüs ve katı program olmadan yirmiden fazla özel rota.",details:"Detayları göster",book:"VIP yolculuğu rezerve et",duration:"ÖZEL",ctaKicker:"KİŞİYE ÖZEL PROGRAM",ctaTitle:"Rotayı ilgi alanlarınıza göre düzenleriz",ctaText:"Durakların sırasını değiştirebilir; restoran, plaj veya seyir noktası ekleyebilirsiniz. Operatör özel fiyat hazırlayacaktır.",ctaButton:"Rotayı WhatsApp'ta görüşün",home:"Ana sayfa",services:"Tüm hizmetler",backMobile:"Geri"},
de:{title:"Private VIP-Tagesreisen an der Küste von Antalya — GoTransfer",meta:"Private VIP-Tagesreisen ab Antalya mit persönlichem Fahrer.",back:"← Leistungen",kicker:"GO TRANSFER · PRIVATE TAGESREISEN",hero:"Private VIP-Tagesreisen an der Küste von Antalya",lead:"Wir holen Sie morgens am Hotel ab, begleiten Sie auf Ihrer Wunschroute und bringen Sie abends zurück. Ihr privates Fahrzeug, persönlicher Fahrer und ein flexibles Programm.",choose:"VIP-Reise auswählen",listKicker:"ABFAHRT AM MORGEN · RÜCKKEHR AM ABEND",listTitle:"Wählen Sie Ihren Tag an der Küste",listText:"Mehr als zwanzig private Routen ohne Gruppen, Reisebusse oder starren Zeitplan.",details:"Details ansehen",book:"VIP-Reise buchen",duration:"PRIVAT",ctaKicker:"INDIVIDUELLES PROGRAMM",ctaTitle:"Wir passen die Route an Ihre Interessen an",ctaText:"Ändern Sie die Reihenfolge der Stopps oder ergänzen Sie Restaurant, Strand oder Aussichtspunkt. Der Operator erstellt ein persönliches Angebot.",ctaButton:"Route über WhatsApp besprechen",home:"Startseite",services:"Alle Leistungen",backMobile:"Zurück"},
ar:{title:"رحلات يومية خاصة على طول ساحل أنطاليا — GoTransfer",meta:"رحلات يومية خاصة لكبار الشخصيات من أنطاليا مع سائق خاص.",back:"الخدمات →",kicker:"GO TRANSFER · رحلات يومية خاصة",hero:"رحلات يومية خاصة على طول ساحل أنطاليا",lead:"نقلكم من الفندق صباحاً، وقضاء اليوم على المسار المختار، ثم إعادتكم مساءً. سيارة خاصة وسائق شخصي وبرنامج مرن يناسب وتيرتكم.",choose:"اختر رحلة كبار الشخصيات",listKicker:"انطلاق صباحاً · عودة مساءً",listTitle:"اختاروا يومكم على الساحل",listText:"أكثر من عشرين مساراً خاصاً من دون مجموعات أو حافلات أو برنامج زمني صارم.",details:"عرض التفاصيل",book:"احجز الرحلة",duration:"رحلة خاصة",ctaKicker:"برنامج مصمم لكم",ctaTitle:"نكيّف المسار حسب اهتماماتكم",ctaText:"يمكن تغيير ترتيب المحطات أو إضافة مطعم أو شاطئ أو منصة مشاهدة. يقدّم مسؤول الحجز سعراً مخصصاً.",ctaButton:"ناقش المسار عبر WhatsApp",home:"الرئيسية",services:"جميع الخدمات",backMobile:"رجوع"}
};
function localizedItems(language){
  if(language==="ru")return window.VIP_JOURNEYS;
  return window.VIP_JOURNEYS.map((item,index)=>{
    const title=titles[language][index];
    const description=language==="ar"?`رحلة خاصة ليوم واحد إلى ${title} بسيارة مريحة وسائق خاص. ننسّق أوقات التوقف والغداء بما يناسب وتيرتكم، مع العودة إلى الفندق مساءً.`:language==="de"?`Private Tagesreise nach ${title} in einem komfortablen Fahrzeug mit persönlichem Fahrer. Stopps, Mittagessen und Tagesrhythmus werden individuell abgestimmt; am Abend kehren Sie zum Hotel zurück.`:language==="tr"?`${title} için konforlu araç ve kişisel şoförle özel bir günlük yolculuk. Duraklar, yemek ve günün temposu size göre planlanır; akşam otelinize dönersiniz.`:`A private day journey to ${title} in a comfortable vehicle with a personal chauffeur. Stops, lunch and timing are tailored to you, with an evening return to your hotel.`;
    const hours=item.duration.replace("часов","").trim();
    const duration=language==="ar"?`${hours} ساعات`:language==="de"?`${hours} Stunden`:language==="tr"?`${hours} saat`:`${hours} hours`;
    const stops=language==="ar"?["الاستقبال من الفندق بسيارة خاصة",`زيارة أهم معالم ${title}`, "توقف مرن للغداء والاستراحة","العودة إلى الفندق مساءً"]:language==="de"?["Abholung am Hotel im Privatfahrzeug",`Besuch der wichtigsten Ziele von ${title}`,"Flexible Pause für Mittagessen und Erholung","Rückkehr zum Hotel am Abend"]:language==="tr"?["Özel araçla otelden alınış",`${title} rotasının başlıca noktaları`,"Yemek ve dinlenme için esnek mola","Akşam otele dönüş"]:["Private pickup from your hotel",`The main highlights of ${title}`,"A flexible stop for lunch and relaxation","Evening return to your hotel"];
    return {...item,title,description,duration,stops};
  });
}
window.JourneyLocales={page,titles,items:localizedItems,getPage:language=>page[language]||page.ru};
})();
