const slug=location.pathname.split("/").filter(Boolean).pop();
function ensureMeta(property){let meta=document.head.querySelector(`meta[property="${property}"]`);if(!meta){meta=document.createElement("meta");meta.setAttribute("property",property);document.head.appendChild(meta)}return meta}
function bookingUrl(title,language){const text=language==="ar"?`مرحباً، أود حجز رحلة كبار الشخصيات «${title}».`:language==="de"?`Guten Tag! Ich möchte die VIP-Reise „${title}“ buchen.`:language==="tr"?`Merhaba! “${title}” VIP yolculuğunu rezerve etmek istiyorum.`:language==="en"?`Hello! I would like to book the VIP journey “${title}”.`:`Здравствуйте! Хочу забронировать VIP-путешествие «${title}».`;return`https://wa.me/905346801828?text=${encodeURIComponent(text)}`}
const placeCopy={
ru:{kicker:"ОСТАНОВКИ МАРШРУТА",title:"Что вас ждёт в путешествии",lead:"Каждое место показано отдельно: что здесь можно увидеть и почему стоит сделать остановку.",number:"Остановка"},
en:{kicker:"PLACES ON YOUR ROUTE",title:"What awaits you on this journey",lead:"Explore every stop, what you can see there and why it deserves time in your private itinerary.",number:"Stop"},
tr:{kicker:"ROTANIZDAKİ DURAKLAR",title:"Bu yolculukta sizi neler bekliyor",lead:"Her durağı, görülecek yerleri ve kişisel programınızda neden zaman ayırmaya değer olduğunu keşfedin.",number:"Durak"},
de:{kicker:"STOPPS AUF IHRER ROUTE",title:"Das erwartet Sie auf dieser Reise",lead:"Entdecken Sie jeden Stopp, seine Sehenswürdigkeiten und warum er Zeit in Ihrer privaten Route verdient.",number:"Stopp"},
ar:{kicker:"محطات المسار",title:"ما الذي ينتظركم في هذه الرحلة؟",lead:"تعرّفوا إلى كل محطة، وما يمكن رؤيته فيها، ولماذا تستحق وقتاً ضمن برنامجكم الخاص.",number:"المحطة"}
};
function renderDetail(language=window.GoTransferLocale?.get()||"ru"){
const page=window.JourneyLocales.getPage(language),data=window.JourneyLocales.items(language).find(item=>item.slug===slug);if(!data){location.replace(`/journeys?lang=${language}`);return}
const russianData=window.VIP_JOURNEYS.find(item=>item.slug===slug);
window.GoTransferLocale?.applyDocument(language);const title=`${data.title} — ${page.hero} | GoTransfer`;document.title=title;document.querySelector('meta[name="description"]').content=data.description;ensureMeta("og:title").content=title;ensureMeta("og:description").content=data.description;
document.querySelector("#detailImage").src=data.image;document.querySelector("#detailImage").alt=data.title;document.querySelector("#detailKicker").textContent=`${page.duration} · ${data.duration}`;document.querySelector("#detailTitle").textContent=data.title;document.querySelector("#detailLead").textContent=data.description;document.querySelector("#detailDuration").textContent=data.duration;document.querySelector("#detailStops").innerHTML=data.stops.map(stop=>`<li>${stop}</li>`).join("");
const placesText=placeCopy[language]||placeCopy.ru;document.querySelector("#detailPlacesKicker").textContent=placesText.kicker;document.querySelector("#detailPlacesTitle").textContent=placesText.title;document.querySelector("#detailPlacesLead").textContent=placesText.lead;
const placeDetails=window.JourneyShowcases.details(data.slug,russianData?.stops||data.stops,data.stops,language);document.querySelector("#detailPlaceCards").innerHTML=placeDetails.map((place,index)=>`<article class="detail-place-card"><div class="detail-place-card__image"><img src="${place.image}" alt="${place.title}" loading="${index<2?"eager":"lazy"}" decoding="async"><span>${String(index+1).padStart(2,"0")}</span></div><div class="detail-place-card__copy"><p>${placesText.number} ${index+1}</p><h3>${place.title}</h3><span>${place.description}</span></div></article>`).join("");
const labels=language==="ar"?["جميع الرحلات →","عرض البرنامج","مثال للبرنامج","ما الذي يمكن زيارته","البرنامج","مدة الرحلة","نقطة الانطلاق","أنطاليا أو فندقكم","البرنامج","مرن حسب رغبتكم","رحلة حسب وتيرتكم","يعمل السائق والسيارة لكم وحدكم طوال اليوم. نستقبلكم صباحاً من الفندق أو من العنوان المتفق عليه، ثم نعيدكم مساءً.","احجز الرحلة","اختر رحلة أخرى","الرئيسية","رجوع"]:language==="de"?["← Alle Reisen","Programm ansehen","BEISPIELPROGRAMM","Was Sie sehen können","FORMAT","Dauer","Beginn","Antalya oder Ihr Hotel","Programm","Flexibel nach Ihren Wünschen","Reisen in Ihrem Rhythmus","Fahrzeug und Fahrer stehen den ganzen Tag ausschließlich Ihnen zur Verfügung. Morgens holen wir Sie am Hotel oder der vereinbarten Adresse ab und bringen Sie am Abend zurück.","VIP-Reise buchen","Andere Reise auswählen","Startseite","Zurück"]:language==="tr"?["← Tüm yolculuklar","Programı görüntüle","ÖRNEK PROGRAM","Neler görülebilir","FORMAT","Süre","Başlangıç","Antalya veya oteliniz","Program","İsteğinize göre esnek","Sizin ritminizde yolculuk","Araç ve şoför gün boyunca yalnızca size hizmet eder. Sabah otelinizden veya belirlenen adresten alınır, akşam geri bırakılırsınız.","VIP yolculuğu rezerve et","Başka yolculuk seç","Ana sayfa","Geri"]:language==="en"?["← All journeys","View programme","SAMPLE PROGRAMME","What you can see","FORMAT","Duration","Start","Antalya or your hotel","Programme","Flexible to your wishes","Travel at your own pace","The vehicle and chauffeur are exclusively yours for the entire day. We collect you from your hotel or agreed address in the morning and return you in the evening.","Book the VIP journey","Choose another journey","Home","Back"]:["← Все путешествия","Посмотреть программу","ПРИМЕР ПРОГРАММЫ","Что можно увидеть","ФОРМАТ","Продолжительность","Начало","Анталия или ваш отель","Программа","Меняется по вашему желанию","Путешествие в вашем ритме","Автомобиль и водитель работают только для вас. Утром мы заберём вас из отеля или по согласованному адресу, а вечером вернём обратно.","Забронировать VIP-путешествие","Выбрать другое путешествие","Главная","Назад"];
document.querySelector("header nav>a:first-child").textContent=labels[0];document.querySelector(".detail-hero article>a").textContent=labels[1];const program=document.querySelector(".detail-content>article");program.querySelector("p").textContent=labels[2];program.querySelector("h2").textContent=labels[3];const aside=document.querySelector(".detail-content aside");aside.querySelector(":scope>p").textContent=labels[4];const terms=aside.querySelectorAll("dt"),defs=aside.querySelectorAll("dd");terms[0].textContent=labels[5];terms[1].textContent=labels[6];defs[1].textContent=labels[7];terms[2].textContent=labels[8];defs[2].textContent=labels[9];document.querySelector(".detail-story>p").textContent=labels[10];document.querySelector("#storyTitle").textContent=data.title;document.querySelector("#detailStory").innerHTML=`<p>${labels[11]}</p><p>${data.description}</p>`;const whatsapp=document.querySelector("#detailWhatsapp");whatsapp.textContent=labels[12];whatsapp.href=bookingUrl(data.title,language);const footer=document.querySelectorAll("footer a");footer[0].textContent=labels[13];footer[0].href=`/journeys?lang=${language}`;footer[1].textContent=labels[14];document.querySelector(".mobile-back-button span").textContent=labels[15];
}
renderDetail();window.addEventListener("gotransfer:languagechange",event=>renderDetail(event.detail.language));
