const form=document.querySelector("#vipRequestForm"),whatsapp=document.querySelector("#vipWhatsApp"),status=document.querySelector("#vipStatus"),date=form.elements.date;
const serviceMap={"Свадебный VIP-трансфер":"Свадьба","Деловые встречи и бизнес-трансфер":"Деловая встреча","Конференции и корпоративные мероприятия":"Конференция","Встреча VIP-гостей":"Встреча VIP-гостей","Рестораны и особые вечера":"Ресторан или особый вечер","Трансфер к яхтам и в марины":"Яхта или марина","Торжества и частные мероприятия":"Частное мероприятие","Индивидуальные VIP-путешествия":"Индивидуальное путешествие"};
const today=new Date(),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const iso=value=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;date.min=iso(today);date.value=iso(tomorrow);
const messageCopy={
ru:{hello:"Здравствуйте! Хочу заказать VIP-транспорт.",labels:["Тип услуги","Дата","Время","Место подачи","Место назначения","Количество пассажиров","Продолжительность","Дополнительные пожелания"],empty:"не указано",done:"Заявка подготовлена. Нажмите «Написать в WhatsApp», чтобы отправить детали оператору."},
en:{hello:"Hello! I would like to book VIP transport.",labels:["Service","Date","Time","Pickup location","Destination","Passengers","Duration","Additional requests"],empty:"not specified",done:"Your request is ready. Select “Message on WhatsApp” to send the details to our booking team."},
tr:{hello:"Merhaba! VIP ulaşım rezervasyonu yapmak istiyorum.",labels:["Hizmet","Tarih","Saat","Alış noktası","Varış noktası","Yolcu sayısı","Süre","Ek talepler"],empty:"belirtilmedi",done:"Talebiniz hazır. Ayrıntıları ekibimize göndermek için “WhatsApp'tan yazın” seçeneğine dokunun."},
de:{hello:"Guten Tag! Ich möchte einen VIP-Fahrservice buchen.",labels:["Leistung","Datum","Uhrzeit","Abholort","Ziel","Fahrgäste","Dauer","Zusätzliche Wünsche"],empty:"nicht angegeben",done:"Ihre Anfrage ist vorbereitet. Wählen Sie „Über WhatsApp schreiben“, um die Angaben an unser Buchungsteam zu senden."},
ar:{hello:"مرحباً، أود حجز خدمة نقل لكبار الشخصيات.",labels:["الخدمة","التاريخ","الوقت","مكان الانطلاق","الوجهة","عدد الركاب","المدة","الطلبات الإضافية"],empty:"غير محدد",done:"تم إعداد طلبك. اضغط على «تواصل عبر WhatsApp» لإرسال التفاصيل إلى مسؤول الحجز."}
};
function language(){return window.GoTransferLocale?.get?.()||"ru"}
function message(){const data=new FormData(form),copy=messageCopy[language()]||messageCopy.ru,values=[data.get("service"),data.get("date"),data.get("time"),data.get("pickup"),data.get("destination"),data.get("passengers"),data.get("duration"),data.get("comment")];return[copy.hello,...copy.labels.map((label,index)=>`${label}: ${values[index]||copy.empty}`)].join("\n")}
function update(){whatsapp.href=`https://wa.me/905346801828?text=${encodeURIComponent(message())}`}
document.querySelectorAll(".vip-card .card-buttons a").forEach(link=>link.addEventListener("click",event=>{event.stopPropagation();const card=link.closest(".vip-card");form.elements.service.value=serviceMap[card.dataset.service]||"Другое";update()}));
form.addEventListener("input",update);form.addEventListener("submit",event=>{event.preventDefault();if(!form.reportValidity())return;update();status.textContent=(messageCopy[language()]||messageCopy.ru).done;whatsapp.focus()});update();
